### ISSUE TITLE
Table Extraction format

### ISSUE THREAD

**Issue by Dipankar1997161** [SuleyNL/Extractable#178]
Hello @SuleyNL,

Thank you for the awesome work. I was wondering if it is possible to extract the tables in some other format other than xml? 
like csv or json or any other. 

I will be waiting for your response

**Comment by SuleyNL** [comment]
Hi, @Dipankar1997161,
Yes thats possible!
Many filetypes are supported. But not all of these have been tested yet.
Supported Filetypes can be seen in the Extractable.Filetypes.py file:

```
class Filetype(str, Enum):
    EXCEL = 'xlsx'
    LATEX = 'tex'
    PARQUET = 'parquet'
    PDF = 'pdf'
    IMG = 'img'
    XML = 'xml'
    JSON = 'json'
    CSV = 'csv'
    HTML = 'html'
    YAML = 'yaml'
```

You can provide the desired Filetype when calling any of the extract() functions like so:

```
import extractable as ex
ex.extract(input_file, output_dir,  output_filetype=ex.Filetype.CSV)
```
This should output your desired filetypes in the output_dir.



> Keep in mind Extractable is still a work in progress, so you can contribute by leaving valuable feedback or by making changes in the code.
